# User settings
# You can change the values, but please don't remove them.
usera:
  # The link of the wise timetable schedule you want the program to download.
  # (to find out where to get this link look in this projects README.md under configuration > schedule)
  url: "https://www.wise-tt.com/wtt_um_feri/index.jsp?filterId=0;79;0;0;"

  groups:
    -
      name: "METODE IN TEHNOLOGIJE KOMUNICIRANJA"
      group:
        - "RV 1. sk."
        - "2" # This will work just as well
    -
      name: "REŠEVANJE PROBLEMOV S PROGRAMIRANJEM"
      group:
        - "RV 2. sk."

# Application settings
# You can change the values, but please don't remove them.
app:
  # This variable specifies where to save the geckodriver used
  # for creating and running the browser.
  # This is only needed when the program can't find the geckodriver in any of the $PATH's maps.
  # The location tells the program where to save the downloaded geckodriver.
  # You can change the location to somewhere else, but it has to be
  # included in the $PATH!
  geckoLocationDownload: "~/.local/bin"