user:
  # TODO: add a description of using the url for the user
  url: "https://www.wise-tt.com/wtt_um_feri/index.jsp?filterId=0;79;0;0;"

  # TODO: explain how one can add diffrent groups and the group numbers
  groups:
    -
      name: "METODE IN TEHNOLOGIJE KOMUNICIRANJA"
      group:
        # TODO: tell them to use the exact or similar group name as in wisetimetable for the program to work
        # TODO: najboljse da jim das dobesedni primer stringa kako naj izpade
        - "RV 1. sk."
    -
      name: "REŠEVANJE PROBLEMOV S PROGRAMIRANJEM"
      group:
        - "RV 2. sk."

# this are configurations settings meant for the application
# configure it if you wish, you won't really do any harm to the application
# accapt if you don't have premission, than you is fuckkked
# TODO: check for premissions for these settings
app:
  # TODO: explain the download folder for easier understanding
  downloadfolder: "./data"


